#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx should  listen on port 80
# Server page returns a Hello World string
# Update package list and install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# Ensure nginx is listening to port 80
ufw allow 'Nginx HTTP'

# Set up the default page
echo "Hello World!" > /var/www/html/index.html

# Restart nginx (without using systemctl)
sudo service nginx restart
