#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend http-in
    timeout client  30000
    bind 0:80
    default_backend servers

backend servers
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 526172-web-01 54.209.131.150 check
    server 526172-web-02 54.175.53.247 check
EOT

sudo service haproxy restart

