#!/usr/bin/env bash
#this script will  displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
#You cannot use pgrep
#The third line of your script must be # shellcheck disable=SC2009

ps -aux --forest | grep "bash"
