#!/usr/bin/env bash
#this script will script that displays To infinity and beyond indefinitely
#In between each iteration of the loop, add a sleep 2

while true
do
	echo "to infinity and beyond"
	sleep 2
done
