#!/usr/bin/env bash
#this script that stops 4-to_infinity_and_beyond process.
#You must use kill

#get the pid of the program
id=$(pgrep ./4-to_infinity_and_beyond)

#terminate the infinit process
kill -15 "$id"
