#!/usr/bin/env bash
#this script that displays:
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

trap 'echo "i am invisible!!!" ' 15
while true
do
	echo "to infinity and beyond"
	sleep 2
done
