#!/usr/bin/env bash
#Displays the contents of the file `/etc/passwd`.
#Only display;
#the username
#user id
#and user home directory path.
#You must use the while loop 
#for and until are forbidden

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"

