#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#You must use the while loop 
#for and until are forbidden

count=0

while [ $count -lt 10 ]
do
  echo "Best School"
  (( count++ ))
done
