#!/usr/bin/env bash
# Displays "Best School" 10 times using an until loop.
#You must use the until loop 
#for and while are forbidden

count=0

until [ $count -eq 10 ]
do
  echo "Best School"
  (( count++ ))
done

