#!/usr/bin/env bash
#Displays the contents of the current directory in list format.
#Only displays the part of the name after the first dash. 
#You must use the for loop 
#while and until are forbidden
#Do not display hidden files

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
